name : CI Pipeline - DEV
on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  RELEASE_TYPE           : 'minor'
  PACKAGE_NAME           : 'osbot_prefect'
  PREFECT_TARGET_SERVER  : ${{ secrets.PREFECT_TARGET_SERVER       }}

jobs:

  start-prefect-server__and-run-tests:
    name: "Start Prefect and Run Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start Prefect Server
        uses: ./.github/actions/docker__start-prefect-server

      - name: Install Dependencies
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/poetry__install@dev
        with:
          pip_install: '-r requirements-test.txt'

      - name: Run Unit Tests
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/poetry__run-unit-tests@dev
        with:
          test_target: 'tests'

#  run-unit-and-integration-tests:
#    #if: False
#    name: "Run Unit & Integration Tests"
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Run Tests and Integration Tests
#        uses: ./.github/actions/pytest__run-unit-and-integration

  increment-tag:
    #if: False
    name: Increment Tag - DEV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment Tag
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          release_type: ${{ env.RELEASE_TYPE }}
    needs:
      - start-prefect-server__and-run-tests

  publish-to-pypi:
    name: "Publish to: PYPI"
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Git Update Current Branch
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__update_branch@dev

      - name: publish-to-pypi
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/pypi__publish@dev
    needs:
      - increment-tag